version: '2'
services:
    atrust:
        image: hagb/docker-atrust:chromium
        devices:
          - /dev/net/tun
        cap_add:
          - NET_ADMIN
        volumes:
          - $HOME/.atrust-data:/root
        environment:
          - CHROMIUM=1
          - PASSWORD=${VNC_PASSWORD}
          - USE_NOVNC=1
        ports:
          - "${BIND_HOST}:39901:5901"
          - "${BIND_HOST}:39902:8080"
          - "${BIND_HOST}:39903:1080"
          - "${BIND_HOST}:39904:8888"
