version: '2'
services:
    atrust:
        image: hagb/docker-atrust:chromium
        devices:
          - /dev/net/tun
        cap_add:
          - NET_ADMIN
        volumes:
          - $HOME/.atrust-data:/root
        environment:
          - CHROMIUM=1
          - PASSWORD=your_vnc_password
          - USE_NOVNC=1
        ports:
          - "0.0.0.0:39901:5901"
          - "0.0.0.0:39902:8080"
          - "0.0.0.0:39903:1080"
          - "0.0.0.0:39904:8888"
